package com.study.bean;

public class Lock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lock.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lock.lockName
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private String lockname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lock.id
     *
     * @return the value of t_lock.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lock.id
     *
     * @param id the value for t_lock.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lock.lockName
     *
     * @return the value of t_lock.lockName
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public String getLockname() {
        return lockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lock.lockName
     *
     * @param lockname the value for t_lock.lockName
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setLockname(String lockname) {
        this.lockname = lockname == null ? null : lockname.trim();
    }
}