package com.study.bean;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.class_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.address
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.birth_date
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    private Date birthDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_name
     *
     * @return the value of t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_name
     *
     * @param teacherName the value for t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.class_name
     *
     * @return the value of t_teacher.class_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.class_name
     *
     * @param className the value for t_teacher.class_name
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.address
     *
     * @return the value of t_teacher.address
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.address
     *
     * @param address the value for t_teacher.address
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.birth_date
     *
     * @return the value of t_teacher.birth_date
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.birth_date
     *
     * @param birthDate the value for t_teacher.birth_date
     *
     * @mbg.generated Wed Nov 20 23:06:44 CST 2019
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
}